ssk/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow')
]

ssk/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'


urlpatterns = [
    path('', views.start, name='start'),
    # 영화 리스트
    path('index/', views.movie_list, name='movie_list'),
    # 영화 디테일
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/review_create/', views.review_c, name='review_c' ),
    path('<int:movie_id>/movie_comments/', views.moive_comment_create, name='moive_comment_create'),
    path('<int:movie_id>/movie_comments/<int:comment_id>/comment_delete/', views.movie_comment_delete, name='movie_comment_delete'),
    path('<int:movie_id>/movie_comments/<int:comment_id>/comment_update/', views.movie_comment_update, name='movie_comment_update'),
    # 리뷰 리스트
    path('review_list/', views.review_list, name='review_list'),
    path('review_create/', views.review_create, name='review_create'),
    # 리뷰 디테일
    path('<int:movie_id>/<int:review_id>/', views.review_detail, name='review_detail'),
    path('<int:movie_id>/<int:review_id>/review_update/', views.review_update, name='review_update'),
    path('<int:movie_id>/<int:review_id>/review_delete/', views.review_delete, name='review_delete'),
    path('<int:movie_id>/<int:review_id>/review_comments/', views.review_comment_create, name='review_comment_create'),
    path('<int:movie_id>/<int:review_id>/review_comments/<int:comment_id>/comment_delete/', views.review_comment_delete, name='review_comment_delete'),
    path('<int:movie_id>/<int:review_id>/like/', views.like, name='like'),
]

ssk/ssk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

ssk/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://kit.fontawesome.com/1288ca63f1.js" crossorigin="anonymous"></script>
    <title>GOD FILM</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Raleway:wght@200;300&family=Suez+One&display=swap" rel="stylesheet">
    <style>
      .footer {text-align: center; width: 100%; margin-top: 300px;}
      .footer > img {width: 200px; margin-left: -20px;}
      p {font-family: 'Raleway', sans-serif;}
      #back { width: 100%; background-color: #0f0f11;}
      .nav-item {margin-left: 10px;}
      .nav-item > a {font-family: 'Suez One', serif; color: white;}
      .nav-item > a:hover {color: #ea1f4f}
      h1, h5 {font-family: 'Suez One', serif;}
      .movie-overview {display: none;}
      .movie-card:hover .movie-overview {display: inline-block;}
      .movie-card:hover .movie-content {border: solid #ea1f4f; border-radius: 5px;}
      .goprofile {text-decoration:none; font-family: 'Suez One', serif; color: #ea1f4f; border-radius: 50px; }
      .goprofile:hover {text-decoration:none; border-radius: 50px; background-color: #ea1f4f; color: white;}
      .review-more {font-family: 'Suez One', serif; border-radius: 50px; padding:2px 5px; background-color: #ea1f4f; color: white;}
      .comment-score {font-family: 'Suez One', serif; border-radius: 50px; padding:1px 9px; background-color: #ea1f4f; color: white; margin-right: 12px;}

      .delete-btn {font-family: 'Suez One', serif;}
      .delete-btn:hover {color: #ea1f4f}
      .opinion {margin-top: 100px;}
      .commtent-btn {font-family: 'Suez One', serif; border-radius: 50px; padding:2px 5px; background-color: #ea1f4f; color: white;}
      .review-create {font-family: 'Suez One', serif; border-radius: 50px; padding:2px 5px; background-color: #ea1f4f; color: white; margin-top:50px}
      .review-th > th {font-family: 'Suez One', serif;}
      .review-td > th {font-family: 'Suez One', serif;}
      .review-td > td > a {text-decoration: none; font-family: 'Nanum Gothic', sans-serif; color:white;}
      .review-td > td > a:hover {color: #ea1f4f; font-weight: bold;}
      .review-movie:hover {color: #ea1f4f;}
      .follow-info > span {font-family: 'Suez One', serif; color: white; border-radius: 50px; padding:2px 5px; background-color: #ea1f4f; display: inline-block; padding: 2px 6px;}
      /* .follower-list {display: none;}
      .follower-list {display: none;}

      .following-list > span {font-family: 'Suez One', serif; color: #ea1f4f; border-radius: 50px; padding:2px 5px; background-color: white; display: inline-block; padding: 2px 6px;}
      .follower-list > span {font-family: 'Suez One', serif; color: #ea1f4f; border-radius: 50px; padding:2px 5px; background-color: white; display: inline-block; padding: 2px 6px;}
      
      .following-num:hover .follower-list{display: block;} */
      
      .comment-update {font-family: 'Suez One', serif; border-radius: 20px; padding:5px 5px 0 5px; color: #ea1f4f; }
      .comment-update:hover {text-decoration:none; background-color: #ea1f4f; color: white;}

      .comment-more {text-decoration:none; font-family: 'Suez One', serif; color: #ea1f4f; margin-top: 6px;}
      .comment-more:hover {text-decoration:none; border-radius: 50px; padding:2px 10px; background-color: #ea1f4f; color: white;}
      .login-button {border:1px solid #ea1f4f; border-radius: 50px; background-color: white; color: #ea1f4f;}
      .login-button:hover {text-decoration:none; border-radius: 50px; background-color: #ea1f4f; color: white;}
      .average {font-family: 'Suez One', serif; color: white; border-radius: 50px; padding:2px 5px; background-color: #ea1f4f; display: inline-block; padding: 2px 6px; height: 30px;}
      .page-num {font-family: 'Suez One', serif; color: white;}
      .page-num:hover {color: #ea1f4f; text-decoration: none;}
      .page-now {font-family: 'Suez One', serif; color: #ea1f4f;}
    </style>

</head>
<body id="back">
    <nav class="navbar navbar-expand-lg">
      <a class="navbar-brand m-2" href="{% url 'movies:start'%}">
        <img src="{% static 'image/logo.png' %}" alt="" style="width: 120px;">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse  d-flex justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movies:movie_list' %}">MOVIE</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movies:review_list' %}">REVIEW</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' user.username %}">MY PAGE</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container p-5">
      {% block content %}
      {% endblock %}
      <div class="footer">
        <img src="{% static 'image/bottom.png' %}" alt="">
    </div>
    </div>
 
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>