ssk/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow')
]

ssk/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'


urlpatterns = [
    path('', views.start, name='start'),
    # 영화 리스트
    path('index/', views.movie_list, name='movie_list'),
    # 영화 디테일
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/review_create/', views.review_c, name='review_c' ),
    path('<int:movie_id>/movie_comments/', views.moive_comment_create, name='moive_comment_create'),
    path('<int:movie_id>/movie_comments/<int:comment_id>/comment_delete/', views.movie_comment_delete, name='movie_comment_delete'),
    path('<int:movie_id>/movie_comments/<int:comment_id>/comment_update/', views.movie_comment_update, name='movie_comment_update'),
    # 리뷰 리스트
    path('review_list/', views.review_list, name='review_list'),
    path('review_create/', views.review_create, name='review_create'),
    # 리뷰 디테일
    path('<int:movie_id>/<int:review_id>/', views.review_detail, name='review_detail'),
    path('<int:movie_id>/<int:review_id>/review_update/', views.review_update, name='review_update'),
    path('<int:movie_id>/<int:review_id>/review_delete/', views.review_delete, name='review_delete'),
    path('<int:movie_id>/<int:review_id>/review_comments/', views.review_comment_create, name='review_comment_create'),
    path('<int:movie_id>/<int:review_id>/review_comments/<int:comment_id>/comment_delete/', views.review_comment_delete, name='review_comment_delete'),
    path('<int:movie_id>/<int:review_id>/like/', views.like, name='like'),
]

ssk/ssk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

ssk/movies/models.py
from django.db import models
from django.conf import settings


# Create your models here.


class Cast(models.Model):
    character = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    poster_path = models.CharField(max_length=200, null=True)
    overview = models.TextField(blank=True)
    gender = models.IntegerField()
    profile_path = models.CharField(max_length=200, null=True)
    imdb_id = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField(blank=True)
    poster_path = models.CharField(max_length=200, null=True)
    cast = models.ManyToManyField(Cast, related_name='cast_movie', blank=True)

    def __str__(self):
        return self.title
    

class Review(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews', blank=True)



class MovieComment(models.Model):
    score = models.IntegerField()
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class ReviewComment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

ssk/movies/forms.py
from django import forms
from .models import Movie, Review, MovieComment, ReviewComment
import requests
import json


class ReviewForm(forms.ModelForm):
    

    class Meta:
        model = Review
        fields = ['title', 'content', 'movie']


class ReviewForm2(forms.ModelForm):

    
    class Meta:
        model = Review
        fields = ['title', 'content']


class MovieCommentForm(forms.ModelForm):
    score = forms.IntegerField(
        label='score',
        min_value=0,
        max_value=10,
    )

    # score = forms.IntegerField(widget = forms.Select())

    class Meta:
        model = MovieComment
        fields = ['score', 'content']


class ReviewCommentForm(forms.ModelForm):
    

    class Meta:
        model = ReviewComment
        fields = ['content']

ssk/movies/views.py
import requests
import json
from django.http import JsonResponse
from django.db.models import Avg
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import Movie, Review, MovieComment, ReviewComment
from .forms import ReviewForm, ReviewForm2, MovieCommentForm, ReviewCommentForm

# Create your views here.


def start(request):
    return render(request, 'movies/start.html')


def movie_list(request):
    movies = Movie.objects.all()
    if request.user.is_authenticated:
        if request.user.moviecomment_set.count() != 0: # 사용자의 데이터가 있는 경우
            # 점수를 기준으로 내림차순 정렬한다.
            cast_list = request.user.moviecomment_set.order_by('-score')[0].movie.cast.all()
            # 영화 배우들 중 제일 처음 배우를 고른다.
            actor = cast_list[0]
            # 배우가 출연한 영화 제목에 'trailer'를 뒤에 붙여 인풋값을 만든다.
            inputvalue = actor.title + 'trailer'
        else: # 인증된 사용자이나, 데이터가 없는 경우 최근에 별점을 부여받은 영화를 사용한다.
            movie = Movie.objects.order_by('-moviecomment')[0]
            # 해당 영화 뒤에 'trailer'를 붙여 인풋값 생성한다.
            inputvalue = movie.title + 'trailer'

    else: # 인증되지 않은 사용자의 경우
        movie = Movie.objects.order_by('-moviecomment')[0]
        inputvalue = movie.title + 'trailer'

    url = 'https://www.googleapis.com/youtube/v3/search'

    # youtube api 키를 따로 secrets.json파일을 만들어서 사용
    youtube_key = getattr(settings, 'YOUTUBE_KEY', 'localhost')

    # url을 통해 넘겨줄 필수 인자들을 정한다.
    # 검색과 관련된 q태그에 인풋값을 연결시켜준다.
    params = {
        'key': youtube_key,
        'part': 'snippet',
        'type': 'video',
        'maxResults': '1',
        'q': inputvalue,
    }

    # url을 통해 얻은 응답을 json형태로 받음
    response = requests.get(url, params)
    response_dict = response.json()

    paginator = Paginator(movies, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # json 파일에서 'items' 키값으로 필요한 value값에 접근한다.
    context = {
        'movies': movies,
        'page_obj': page_obj,
        'youtube_items': response_dict['items'],
    }
    return render(request, 'movies/movie_list.html', context)


def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    reviews = movie.review_set.all()
    comments = movie.moviecomment_set.all()
    comments_count = movie.moviecomment_set.count()
    if comments_count != 0:
        score = movie.moviecomment_set.all().aggregate(Avg('score'))
        averages = score['score__avg']
        average = int(averages)

        # average = 
        comment_form = MovieCommentForm()
        context = {
            'comments_count': comments_count,
            'movie': movie,
            'reviews': reviews,
            'comments': comments,
            'comment_form': comment_form,
            'average': average
        }

    else:
        comment_form = MovieCommentForm()
        context = {
            'comments_count': comments_count,
            'movie': movie,
            'reviews': reviews,
            'comments': comments,
            'comment_form': comment_form,
        }
    return render(request, 'movies/movie_detail.html', context)


def review_list(request):
    reviews = Review.objects.all()
    context =  {
        'reviews': reviews
    }
    return render(request, 'movies/review_list.html', context)


@login_required
def review_create(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            # review.movie = movie
            review.save()
            return redirect('movies:review_detail', review.movie.id, review.id)

    else:
        review_form = ReviewForm()

    context = {
        'review_form': review_form,
    }
    return render(request, 'movies/review_create.html', context)


@login_required
def review_detail(request, movie_id, review_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)
    comments = review.reviewcomment_set.all()
    comment_form = ReviewCommentForm()
    context = {
        'movie': movie,
        'review': review,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'movies/review_detail.html', context)


@login_required
def review_c(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        review_form = ReviewForm2(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.movie = movie
            review.save()
            return redirect('movies:review_detail', review.movie.id, review.id)

    else:
        review_form = ReviewForm2()

    context = {
        'movie': movie,
        'review_form': review_form,
    }
    return render(request, 'movies/movie_review.html', context)


@login_required
def review_update(request, movie_id, review_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)
    if request.user == review.user:
        if request.method == 'POST':
            review_form = ReviewForm(request.POST, instance=review)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                review.user = request.user
                review.save()
                return redirect('movies:review_detail', review.movie.id, review.id)
            
        else:
            review_form = ReviewForm(instance=review)

        context = {
            'review_form': review_form,
            'review': review,
            'movie': movie
        }
        return render(request, 'movies/review_create.html', context)


@login_required
@require_POST
def review_delete(request, movie_id, review_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)
    if request.user == review.user:
        review.delete()
    return redirect('movies:review_list')


@login_required
def moive_comment_create(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        comment_form = MovieCommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.movie = movie
            comment.save()
    return redirect('movies:movie_detail', movie.id)


@require_POST
@login_required
def movie_comment_delete(request, movie_id, comment_id):
    comment = get_object_or_404(MovieComment, id=comment_id)
    if comment.user != request.user:
        return redirect(request.POST.get('next') or 'movies:movie_detail', movie_id)
    comment.delete()
    return redirect('movies:movie_detail', movie_id)


@login_required
def movie_comment_update(request, movie_id, comment_id):
    comment = get_object_or_404(MovieComment, id=comment_id)
    if comment.user == request.user:
        if request.method == 'POST':
            comment_form = MovieCommentForm(request.POST, instance=comment)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.user = request.user
                comment.save()
                return redirect('movies:movie_detail', comment.movie.id)

        else:
            comment_form = MovieCommentForm(instance=comment)
        context = {
            'comment_form': comment_form,
        }
        return render(request, 'movies/movie_comment_update.html', context)


@login_required
def review_comment_create(request, movie_id, review_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)
    if request.method == 'POST':
        comment_form = ReviewCommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.review = review
            comment.save()
    return redirect('movies:review_detail', movie.id, review_id)


@require_POST
@login_required
def review_comment_delete(request, movie_id, review_id, comment_id):
    comment = get_object_or_404(ReviewComment, id=comment_id)
    if comment.user != request.user:
        return redirect('movies:review_detail', movie_id, review_id)
    comment.delete()
    return redirect('movies:review_detail', movie_id, review_id)





@login_required
def like(request, movie_id, review_id):
    user = request.user
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)

    if user in review.like_users.all():
        review.like_users.remove(user)
        liked = False

    else:
        review.like_users.add(user)
        liked = True

    context = {
        'count': review.like_users.count(),
        'liked': liked,
    }

    return JsonResponse(context)

ssk/movies/templates/movies/movie_comment_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div>
    <h1 style="color: white;">Comment Update</h1>
    <h5 style="color: white;">Let's Talk with <span style="color: #ea1f4f;">Godfilm</span></h5>
  </div>
  
  <form action="" method="POST" class="mt-5" style="font-family: 'Suez One', serif; color: white;">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
        <button type="submit" class="float-right review-create" style="margin-top: 20px;"> update </button>
    </form>

{% endblock %}

ssk/movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
<div class="d-flex justify-content-between">
  <h1 style="font-family: 'Suez One', serif; color: white;">ABOUT MORE</h1>
  <a href="{% url 'movies:review_c' movie.id %}" class="btn text-white review-btn" 
  style="border-radius: 50px; height: 40px; font-family: 'Suez One', serif; background-color: #ea1f4f;">REVIEW</a>
</div>

<div class=" mb-3" style="width: 100%;">
  <div class="row no-gutters" style="border: solid #ea1f4f; border-radius: 10px;">
    <div class="col-md-4">
      <img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2/{{ movie.poster_path }}" class="card-img" alt="...">
    </div>
    <div class="col-md-8" style="background-color: white;">
      <div class="card-body" style="">
        <h5 class="card-title" style="font-size: 30px; font-family: 'Nanum Gothic', sans-serif;">{{ movie.title }}</h5>
        <p class="card-text" style="font-family: 'Nanum Gothic', sans-serif;">{{ movie.overview }}</p>
        <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
      </div>
    </div>
  </div>
</div>

<h1 class="mt-5" style="font-family: 'Suez One', serif; color: white;">Characters</h1>
<div class="row row-cols-1 row-cols-md-3">
  {% for person in movie.cast.all %}
  <div class="col mb-4">
    <div class="card">
      {% if person.profile_path|length != 0 %}
        <img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2/{{ person.profile_path }}" class="card-img-top" alt="...">
      {% else %}
        <img src="{% static 'image/noprofile.png' %}" class="card-img-top" alt="...">
      {% endif %}
      <div class="card-body">
        <h5 class="card-title" style="font-family: 'Suez One', serif;">{{ person.name }}</h5>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<!-- 리뷰 페이지 -->
<div class="d-flex justify-content-between">
  <h1 style="font-family: 'Suez One', serif; color: #ea1f4f;" class="mt-5">Review</h1>
  <a href="{% url 'movies:review_c' movie.id %}" class="btn text-white review-btn mt-5" 
  style="border-radius: 50px; height: 40px; font-family: 'Suez One', serif; background-color: #ea1f4f;">REVIEW CREATE</a>
</div>
{% for review in reviews %}
  <div class="card mb-2">
    <h5 class="card-header d-flex justify-content-between">
      <div class="d-flex justify-content-end">
      <span style="font-family: 'Nanum Gothic', sans-serif;" class="mr-3"><a href="{% url 'accounts:profile' review.user %}" class="goprofile">{{ review.user }}</a>님의 리뷰</span>
      <span style="font-family: 'Nanum Gothic', sans-serif; font-size: 10px;" class="text-muted mt-2">작성 : {{ review.created_at }} | 수정 : {{ review.updated_at }}</span>
      </div>
      <a href="{% url 'movies:review_detail' movie.id review.id %}" class="btn review-more">MORE</a>
    </h5>
    <div class="card-body">
      <p class="card-text">{{ review.title }}</p>
    </div>
  </div>
{% endfor %}





<div class="d-flex justify-content-between mt-5">
  <h1 style="font-family: 'Suez One', serif; color: #ea1f4f;">Comments</h1>
  {% if comments_count != 0 %}
    <div class="average mt-3">average | {{ average }}</div>
  {% endif %}
</div>
<!--댓글 목록-->
{% if comments_count != 0 %}
	<div class="card">
      {% for comment in comments %}
      <div class="card-body d-flex justify-content-between">
        <div>
          <span style="display: inline-block;" class="comment-score">{{ comment.score }}</span> 
          <span style="display: inline-block;">{{ comment.content }}</span>
        </div>
        
        <div class="d-flex justify-content-end">
          <span style="font-family: 'Nanum Gothic', sans-serif; font-size: 10px;" class="text-muted mt-2">작성 : {{ comment.created_at }} | 수정 : {{ comment.updated_at }}</span>
        {% if comment.user == request.user %}
          <div class="d-flex justify-content-end">
            <a href="{% url 'movies:movie_comment_update' movie.id comment.id %}" class="comment-update">update</a>
            <form action="{% url 'movies:movie_comment_delete' movie.id comment.id %}" method="POST">
              {% csrf_token %}
              <button class="btn delete-btn">X</button>
            </form>
          </div>
        {% endif %}
        </div>
      </div>
      {% endfor %}
  </div>
{% endif %}



<!--사용자 인증된 사람만 댓글 작성해!-->
{% if user.is_authenticated %}
<div class="mb-5">
  <h1 style="font-family: 'Suez One', serif; color: #ea1f4f;" class="opinion">How about you?</h1>
  <form action="{% url 'movies:moive_comment_create' movie.id %}" method="POST" style="font-family: 'Suez One', serif; color: white;">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <button class="commtent-btn float-right">SUBMIT</button>
  </form>
</div>
{% endif %}



<script>
    // const URL = 'https://api.themoviedb.org/3/movie/' + {{ movie.id }} + '?api_key=d689b32a04ce5d8848100e823ed584d7&language=ko-KR'
    
    // axios.get(URL)
    // .then(response => {
    //     console.log(response)
    // })

// const app = new Vue({
//     el: '#movie_detail',
//     data: {
//         overview
//     },
//     methods: {

//     }

// })

</script>
{% endblock %}

ssk/movies/templates/movies/review_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div style="margin-bottom: 50px;">
  <h1 style="color: white;">REVIEW</h1>
  <h5 style="color: white;">Let's Talk with <span style="color: #ea1f4f;">Godfilm</span></h5>
</div>


<div class="card">
  <h5 class="card-header">
    <a href="{% url 'movies:movie_detail' movie.id %}" 
    style="text-decoration:none; font-family: 'Nanum Gothic', sans-serif; font-weight: bold; color:black" class="review-movie">{{ review.movie.title }}</a>
    <div class="float-right">
        {% if request.user in review.like_users.all %}
          <i class="fas fa-heart fa-lg like-button" style="color:crimson" data-movieid="{{ movie.id }}" data-reviewid="{{ review.id }}"></i>
        {% else %}
          <i class="fas fa-heart fa-lg like-button" style="color:gainsboro" data-movieid="{{ movie.id }}" data-reviewid="{{ review.id }}"></i>
        {% endif %}
        <span id="like-count-{{ review.id }}" class="mr-2">{{ review.like_users.all|length }}</span>
      {% if review.user == request.user %}
          <a href="{% url 'movies:review_update' movie.id review.id %}" class="btn update-btn review-more">update</a>
          <form action="{% url 'movies:review_delete' movie.id review.id %}" method="POST" style="display: inline-block;">
              {% csrf_token %}
              <button class="btn delete-btn">X</button>
          </form>
      {% endif %}
      </div>
  </h5>
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <h5 class="card-title" style="font-family: 'Nanum Gothic', sans-serif; font-weight: bold;">{{ review.title }}</h5>
      <span><a href="{% url 'accounts:profile' review.user.username %}" class="btn goprofile" style="margin-top: -5px;">{{ review.user.username }}</a><span class="text-muted">님이 작성한 리뷰입니다.</span></span>
    </div>
    <p class="card-text" style="font-family: 'Nanum Gothic', sans-serif;">{{ review.content }}</p>
  </div>
  <div class="card-footer text-muted" style="font-family: 'Nanum Gothic', sans-serif; text-align: center;">
    작성 : {{ review.created_at }} | 수정 : {{ review.updated_at }}
  </div>
</div>


<h1 style="font-family: 'Suez One', serif; color: white;;" class="mt-5">Comments</h1>
<!--댓글 목록-->
{% if comments.count != 0 %}
	<div class="card">
      {% for comment in comments %}
      <div class="card-body d-flex justify-content-between">
        <div class="mt-1">
          <span><a href="{% url 'accounts:profile' comment.user %}" class="btn goprofile" style="margin-top: -5px;">{{ comment.user }}</a><span class="text-muted">님의 댓글 | </span></span>
          <span style="display: inline-block; font-family: 'Nanum Gothic', sans-serif;" class="text-muted">  {{ comment.content }}</span>
        </div>
        
        <div class="d-flex justify-content-end">
        <span style="display: inline-block; font-family: 'Nanum Gothic', sans-serif;" class="text-muted mt-2">{{ comment.created_at }}</span>
        {% if comment.user == request.user %}
        <form action="{% url 'movies:review_comment_delete' movie.id review.id comment.id %}" method="POST">
          {% csrf_token %}
          <button class="btn delete-btn">X</button>
        </form>
        {% endif %}
      </div>
      </div>
      {% endfor %}
  </div>
{% endif %}

  <div class="mb-5">
    <h1 style="font-family: 'Suez One', serif; color: #ea1f4f;" class="opinion">How about you?</h1>
    <!--사용자 인증된 사람만 댓글 작성해!-->
    {% if user.is_authenticated %}
    <form action="{% url 'movies:review_comment_create' movie.id review.id %}" method="POST" style="font-family: 'Suez One', serif; color: white;">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      <button class="commtent-btn float-right">SUBMIT</button>
    </form>
    {% endif %}
  </div>

  <script>
    const likeButtonList = document.querySelectorAll('.like-button')
      likeButtonList.forEach(likeButton => {
        likeButton.addEventListener('click', function(event){
          console.log(event)
          // -> event.target.dataset.id
          const movieId = event.target.dataset.movieid
          const reviewId = event.target.dataset.reviewid
          {% if user.is_authenticated %}
          axios.get(`/movies/${movieId}/${reviewId}/like/`)
            .then(response => {
              console.log(response)
              // console.log(response) -> data: count, liked
              document.querySelector(`#like-count-${reviewId}`).innerText = response.data.count

              if (response.data.liked) {
                event.target.style.color = 'crimson'
              } else {
                event.target.style.color = 'gainsboro'
              }
            })
            .catch(error => {
              console.log(error)
            })

          {% else %}
          alert('비로그인 사용자는 좋아요 누를 수 없어요!')
          {% endif %}
        })
      })

  </script>

{% endblock %}

ssk/movies/templates/movies/start.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200;300&display=swap" rel="stylesheet">
    <title>GOD FILM</title>
    <style>
        #warp { width: 100%; height: 100%; overflow: hidden; background-color: #0f0f11; }
        .title { width:100%; text-align:center; margin-top: 300px;}
        .title_eng {text-align: center; transition:all ease 0.5s;}
        .title_eng > img { height: 300px;}
        .footer {text-align: center; position: fixed; bottom: 10px; width: 100%;}
        .footer > img {width: 200px; margin-left: 20px;}
        .menu > li {list-style: none; margin-bottom: 40px; font-family: 'Raleway', sans-serif; font-size: 20px;}
        .menu > li > a {text-decoration: none; color: white; opacity:0.6; letter-spacing: 5px}
        .menu {visibility: hidden; transition:all ease 0.5s;}

        .title:hover .title_eng { transform:translateY(-150px); }
        .title:hover .menu {visibility: visible; transform:translateY(-150px);}
        .menu > li > a:hover { opacity: 1; border-radius: 50px; background-color:#ea1f4f; padding: 5px 12px;}
    </style>
</head>

<body id="warp">
    <div id="container">
        <div class="conts">
            <div class="title">
                <div class="title_eng">
                    <img src="{% static 'image/title3.png' %}" alt="">
                </div>
                <ul class="menu">
                    {% if user.is_authenticated %}
                    <li class="logout"><a href="{% url 'accounts:logout' %}">LOGOUT</a></li>
                    <li class="logout"><a href="{% url 'accounts:profile' user.username %}">MY PAGE</a></li>
                    {% else %}
                    <li class="login"><a href="{% url 'accounts:login' %}">LOGIN</a></li>
                    <li class="signup"><a href="{% url 'accounts:signup' %}">SIGNUP</a></li>
                    {% endif %}
                    <li class="movie"><a href="{% url 'movies:movie_list' %}">JUST START</a></li>
                </ul>
            </div> 
            <div class="footer">
                <img src="{% static 'image/bottom.png' %}" alt="">
            </div>
        </div>
    </div>
    


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>