ssk/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow')
]

ssk/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'


urlpatterns = [
    path('', views.start, name='start'),
    # 영화 리스트
    path('index/', views.movie_list, name='movie_list'),
    # 영화 디테일
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/review_create/', views.review_c, name='review_c' ),
    path('<int:movie_id>/movie_comments/', views.moive_comment_create, name='moive_comment_create'),
    path('<int:movie_id>/movie_comments/<int:comment_id>/comment_delete/', views.movie_comment_delete, name='movie_comment_delete'),
    path('<int:movie_id>/movie_comments/<int:comment_id>/comment_update/', views.movie_comment_update, name='movie_comment_update'),
    # 리뷰 리스트
    path('review_list/', views.review_list, name='review_list'),
    path('review_create/', views.review_create, name='review_create'),
    # 리뷰 디테일
    path('<int:movie_id>/<int:review_id>/', views.review_detail, name='review_detail'),
    path('<int:movie_id>/<int:review_id>/review_update/', views.review_update, name='review_update'),
    path('<int:movie_id>/<int:review_id>/review_delete/', views.review_delete, name='review_delete'),
    path('<int:movie_id>/<int:review_id>/review_comments/', views.review_comment_create, name='review_comment_create'),
    path('<int:movie_id>/<int:review_id>/review_comments/<int:comment_id>/comment_delete/', views.review_comment_delete, name='review_comment_delete'),
    path('<int:movie_id>/<int:review_id>/like/', views.like, name='like'),
]

ssk/ssk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

ssk/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followers = models.ManyToManyField(
            settings.AUTH_USER_MODEL,
            related_name='followings'
        )

ssk/movies/models.py
from django.db import models
from django.conf import settings


# Create your models here.


class Cast(models.Model):
    character = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    poster_path = models.CharField(max_length=200, null=True)
    overview = models.TextField(blank=True)
    gender = models.IntegerField()
    profile_path = models.CharField(max_length=200, null=True)
    imdb_id = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField(blank=True)
    poster_path = models.CharField(max_length=200, null=True)
    cast = models.ManyToManyField(Cast, related_name='cast_movie', blank=True)

    def __str__(self):
        return self.title
    

class Review(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews', blank=True)



class MovieComment(models.Model):
    score = models.IntegerField()
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class ReviewComment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

ssk/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):

  class Meta(UserCreationForm.Meta):
    model = get_user_model()
    # fields = UserCreationForm.Meta.fields

ssk/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required

from .forms import CustomUserCreationForm
from movies.models import Movie, Cast, Review




User = get_user_model()

# Create your views here.



def signup(request):
    # 로그인 되어있다면
    if request.user.is_authenticated:
        return redirect('movies:movie_list')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:movie_list')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('movies:movie_list')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:movie_list')

    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:movie_list')


@login_required
def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    if person.moviecomment_set.count() != 0: # 사용자의 코멘트 데이터가 있는 경우
        # 사용자가 부여한 점수를 기준으로 내림차순 정렬을 한 후, 영화의 배우 데이터를 가져온다.
        cast_list = person.moviecomment_set.order_by('-score')[0].movie.cast.all()

    else: # 사용자의 코멘트 데이터가 없는 경우
        # 제일 최근에 코멘트가 달린 영화의 배우 데이터를 가져온다.
        cast_list = Movie.objects.order_by('-moviecomment')[0].cast.all()
 
    context = {
        'person': person,
        'cast_list': cast_list,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, username):
    me = request.user
    you = get_object_or_404(get_user_model(), username=username)

    if me != you:
        if you.followers.filter(id=me.id).exists():
            you.followers.remove(me)
        else:
            you.followers.add(me)
    return redirect('accounts:profile', username)

ssk/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div style="margin-bottom: 50px;">
  <h1 style="color: white;">LOGIN</h1>
  <h5 style="color: white;">Let's enjoy with <span style="color: #ea1f4f;">Godfilm</span></h5>
</div>

<form action="" method="POST" style="font-family: 'Nanum Gothic', sans-serif; color: white;">
  {% csrf_token %}
  {% bootstrap_form form %}
  <div class="d-flex justify-content-end mt-3">
    <button type="submit" class="btn mr-3 login-button" style="font-family: 'Suez One', serif;">LOGIN</button>
    <a href="{% url 'accounts:signup' %}" class="btn" style="border-radius: 50px; background-color: #ea1f4f; color: white; font-family: 'Suez One', serif;">SIGN UP</a>
  </div>
</form>
{% endblock %}

ssk/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
<div class="d-flex justify-content-start">
    <h1 style="color: white;"><span style="color: #ea1f4f;">{{ person.username }}</span>'s Profile</h1>
    {% if user != person %} <!--user = request.user, person = 프로필 주인-->
    <a href="{% url 'accounts:follow' person.username %}" class="mt-3 ml-3">
        {% if user in person.followers.all %}
            <i class="fas fa-user-plus" style="color: #ea1f4f;"></i>
        {% else %}
            <i class="fas fa-user-plus" style="color: white;"></i>
        {% endif %}
    </a>
    {% endif %}
</div>

<div class="follow-info mt-2">
    <span class="mr-2 following-num"> following | {{ person.followings.all|length }}</span>
    <!--<p>팔로워 : {{ person_followings|length }}</p>-->
    <span class="mr-2 follower-num"> follower | {{ person.followers.all|length }}</span>
    <!--<p>팔로워 : {{ person_followers|length }}</p>-->
    <span class="mr-2"> comments | {{ person.moviecomment_set.all|length }}</span>
    <span class="mr-2"> reviews | {{ person.review_set.all|length }}</span>
    <span class="mr-2"> likes | {{ person.like_reviews.all|length }}</span>
    <!-- <div class="following-list mt-3">
        {# for following in person.followings.all #}
        <span class="mr-2">{# following #}</span>
        {# endfor #}
    </div>
    <div class="follower-list mt-3">
      {# for follower in person.followers.all #}
      <span class="mr-2">{# followers #}</span>
      {# endfor #}
    </div> -->
</div>




<!-- 본인에게만 추천 목록 표시 -->
{% if person == user %}
<!-- 추천항목 -->
<h1 class="text-white" style="margin-top: 70px;"> GOD FILM's <span style="color: #ea1f4f;">PICK</span></h1>
<div class="row row-cols-1 row-cols-md-3">
    {% for actor in cast_list %}
    <div class="col mb-4 movie-card">
      <div class="card h-100">
        <!-- 포스터 정보가 없는 경우 처리를 따로 해준다. -->
        {% if actor.poster_path|length != 0%}
          <img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2/{{ actor.poster_path }}" alt="">
        {% else %}
          <img src="{% static 'image/noprofile.png' %}" alt="">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title" style="font-family: 'Nanum Gothic', sans-serif; font-weight:bold">{{ actor.title }}</h5>
          <p class="card-text movie-overview" style="font-family: 'Nanum Gothic', sans-serif;">{{ actor.overview }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endif %}

    


<!-- 리뷰 목록 -->
<div class="d-flex justify-content-start">
    <h1 style="color: white; margin: 70px 0 30px 0;"><span style="color: #ea1f4f;">{{ person.username }}</span>'s Reviews</h1>
    <div class="follow-info" style="margin: 70px 0 30px 0;"><span class="ml-3 mt-3 px-2">{{  person.review_set.count }}</span></div>
</div>
{% for review in person.review_set.all %}
  <div class="card mb-2">
    <h5 class="card-header d-flex justify-content-between">
      <span style="font-family: 'Nanum Gothic', sans-serif; font-weight:bold"><a href="{% url 'accounts:profile' review.user %}" class="goprofile">{{ person.username }}</a>님의 리뷰</span>
      <a href="{% url 'movies:review_detail' review.movie.id review.id %}" class="btn review-more">MORE</a>
    </h5>
    <div class="card-body d-flex justify-content-between">
      <p class="card-text">{{ review.title }}</p>
      {% if review.user == request.user %}
      <form action="{% url 'movies:review_delete' review.movie.id review.id %}" method="POST">
        {% csrf_token %}
        <button class="btn delete-btn">X</button>
      </form>
      {% endif %}
    </div>
  </div>
{% endfor %}


<!-- 코멘트 목록 -->
<div class="d-flex justify-content-start">
    <h1 style="color: white;  margin: 70px 0 30px 0;"><span style="color: #ea1f4f;">{{ person.username }}</span>'s Comments</h1>
    <div class="follow-info" style="margin: 70px 0 30px 0;"><span class="ml-3 mt-3 px-2">{{ person.moviecomment_set.count }}</span></div>
</div>
{% if person.moviecomment_set.count != 0%}
<div class="card">
    {% for moviecomment in person.moviecomment_set.all %}
    <div class="card-body d-flex justify-content-between">
      <div>
        <span style="display: inline-block;">{{ moviecomment.movie.title }}</span> 
        <span style="display: inline-block;" class="comment-score">{{ moviecomment.score }}</span>
      </div>
        <div class="d-flex justify-content-end">
            <span style="font-family: 'Nanum Gothic', sans-serif; font-size: 10px;" class="text-muted mt-2 mr-2">작성 : {{ moviecomment.created_at }} | 수정 : {{ moviecomment.updated_at }}</span>
            <a class="comment-more" href="{% url 'movies:movie_detail' moviecomment.movie.id %}">MORE</a>
            {% if moviecomment.user == request.user %}
            <form action="{% url 'movies:movie_comment_delete' moviecomment.movie.id moviecomment.id %}" method="POST">
                {% csrf_token %}
                <button class="btn delete-btn">X</button>
            </form>
            {% endif %}
        </div>  
    </div>
    {% endfor %}
</div>
{% endif %}


<!--해당 프로필의 유저가 좋아요를 누른 게시물-->
<div class="d-flex justify-content-start">
  <h1 style="color: white; margin: 70px 0 30px 0;"><span style="color: #ea1f4f;">{{ person.username }}</span>'s likes</h1>
  <div class="follow-info" style="margin: 70px 0 30px 0;"><span class="ml-3 mt-3 px-2">{{  person.like_reviews.all.count }}</span></div>
</div>
{% for review in person.like_reviews.all %}
<div class="card mb-2">
  <h5 class="card-header d-flex justify-content-between">
    <div>     
      <span style="font-family: 'Nanum Gothic', sans-serif; font-weight:bold"><a href="{% url 'accounts:profile' review.user %}" class="goprofile mr-1">{{ review.user.username }}</a>님의 리뷰</span>
      <span style="font-family: 'Nanum Gothic', sans-serif; font-size: 10px;" class="text-muted mt-2 ml-2">작성 : {{ review.created_at }} | 수정 : {{ review.updated_at }}</span>
    </div>
    <a href="{% url 'movies:review_detail' review.movie.id review.id %}" class="btn review-more">MORE</a>
  </h5>
  <div class="card-body d-flex justify-content-between">
    <p class="card-text">{{ review.title }}</p>
  </div>
</div>
{% endfor %}



{% endblock %}

ssk/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="margin-bottom: 50px;">
    <h1 style="color: white;">SIGN UP</h1>
    <h5 style="color: white;">Let's enjoy with <span style="color: #ea1f4f;">Godfilm</span></h5>
  </div>

<form action="" method="POST" style="font-family: 'Nanum Gothic', sans-serif; color: white;">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="float-right" style="border-radius: 50px; background-color: #ea1f4f; color: white; font-family: 'Suez One', serif;">SIGN UP</button>
</form>
{% endblock %}